version: '3'

services: 
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500
      - 38080:8080
      
  postgres-db:
    image: postgres
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: example
